apiVersion: v1
kind: Service
metadata:
  name: flamenco-service
  namespace: runai-{{ .Values.runai.project.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.flamenco.port }}
      targetPort: 8080
  selector:
    workloadName: blender-scheduler
  type: ClusterIP
