name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfiles/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfiles/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER }}

    - name: Build and push Blender Worker image
      run: |
        docker build -t ghcr.io/runai-professional-services/blender/blender-worker:0.1 ./Dockerfiles/worker
        docker push ghcr.io/runai-professional-services/blender/blender-worker:0.1

    - name: Build and push Blender Manager image
      run: |
        docker build -t ghcr.io/runai-professional-services/blender/blender-manager:0.1 ./Dockerfiles/manager
        docker push ghcr.io/runai-professional-services/blender/blender-manager:0.1
