name: Release Helm Chart

on:
  push:
    tags:
      - '*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Package Helm Chart
      run: |
        helm package ./path-to-your-chart
        ls -l  # List files to confirm the chart is packaged

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}  # The tag that triggered the workflow
        release_name: "Helm Chart Release ${{ github.ref }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token is automatically provided in Actions

    - name: Upload Helm Chart to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path-to-your-chart/chart-name-*.tgz
        asset_name: chart-name-*.tgz
        asset_content_type: application/gzip
